# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello
namespace: argocd-test
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- route.yaml
